
#  jsp setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp 
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
              
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/gaussdui?allowMultiQueries=true
    username: root
    password: mysql12#$
    dbcp2:
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
# server port binding and 
 # ===============================
server:
  port: 8080
